name: concrete-dam-stability
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cssselect2=0.2.1
  - cycler=0.10.0
  - et_xmlfile=1.0.1
  - freetype=2.10.4
  - geos=3.9.1
  - icu=68.1
  - intel-openmp=2021.3.0
  - jbig=2.1
  - jdcal=1.4.1
  - jpeg=9d
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.7
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.3.0
  - libxml2=2.9.12
  - libxslt=1.1.33
  - lxml=4.6.3
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.3.0
  - numpy=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.8
  - openssl=1.1.1l
  - pandas=1.3.3
  - pillow=8.3.2
  - pip=21.2.4
  - pyparsing=2.4.7
  - pypdf2=1.26.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - qt=5.12.9
  - reportlab=3.5.68
  - setuptools=58.0.4
  - shapely=1.7.1
  - six=1.16.0
  - sqlite=3.36.0
  - svglib=1.1.0
  - tbb=2021.3.0
  - tinycss2=1.1.0
  - tk=8.6.11
  - tornado=6.1
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - webencodings=0.5.1
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
